version: '3'
services:
  recipe_api:
    image: recipe_api:v1 
    build:
      context: .
      dockerfile: Dockerfile
    links:
    - postgres:postgres
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: recipe
      POSTGRES_USER: recipe
      POSTGRES_HOST: postgres
      PORT: 5000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: recipe
      POSTGRES_USER: recipe
